/* Brand section chrome.
 *
 * Two sources feed every Brand story and neither of them is this file:
 *
 *   spec.json      the Marketing Designer's authoritative logo spec, copied
 *                  verbatim out of ofir-agents-cloud/assets/logo/ by
 *                  scripts/build_brand_assets.py. Never hand-edited here.
 *   measured.json  generated by the same script - every geometric number is
 *                  measured off the master artwork, and the construction
 *                  constants are parsed out of the generator source.
 *
 * Same law as Foundations, which reads styles.css at runtime: a design-system
 * page shows values it READS, never values somebody re-typed into it.
 *
 * Page chrome (cards, borders, type) uses the site's own --pl-* tokens so the
 * Brand section looks like the rest of the Storybook. The STAGES use the brand's
 * own approved grounds, because those are facts about the logo, not about this page.
 */
import spec from './spec.json';
import measured from './measured.json';

export { spec, measured };

export const G = measured.grounds; // cream / paper / dark, parsed from export_lockups.py
export const ORDER = spec.icon.reading_order; // yellow, orange, purple, teal - fixed

/* Asset URLs are relative, exactly like the site's own assets in the other
 * stories, so they resolve under the /storybook/ subpath in production too. */
export const A = (file) => `brand/${file}`;

export const mono =
  'font:600 12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;direction:ltr;unicode-bidi:isolate;text-align:left';

export function lead(html) {
  return `<p class="section-lead" style="max-width:76ch;margin:0 0 20px">${html}</p>`;
}

export function h(text) {
  return `<h3 style="font-size:var(--text-h3,1.15rem);font-weight:700;margin:28px 0 10px">${text}</h3>`;
}

export function card(inner, pad = '18px') {
  return `<div style="background:var(--pl-surface);border:1px solid var(--pl-border);
    border-radius:var(--radius-md);padding:${pad}">${inner}</div>`;
}

/* A stage is the brand ground, not the page ground. `tone` picks one of the three
 * approved grounds; nothing else is ever a legal ground for the mark. */
export function stage(inner, tone = 'cream', pad = '40px') {
  return `<div style="background:${G[tone]};border:1px solid var(--pl-border);
    border-radius:var(--radius-md);padding:${pad};display:grid;place-items:center">${inner}</div>`;
}

export function caption(text) {
  return `<div style="${mono};font-weight:500;color:var(--pl-fg-secondary);margin-top:8px">${text}</div>`;
}

export function figure(inner, cap, tone = 'cream', pad = '40px') {
  return `<figure style="margin:0">${stage(inner, tone, pad)}
    <figcaption style="${mono};font-weight:500;color:var(--pl-fg-secondary);margin-top:8px">${cap}</figcaption>
  </figure>`;
}

export function grid(cells, min = '280px', gap = '16px', align = 'stretch') {
  return `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(${min},1fr));
    gap:${gap};align-items:${align}">${cells.join('')}</div>`;
}

/* Rule cards. `no` is a hard prohibition, `yes` is a standing instruction. */
export function rule(kind, title, body) {
  const edge = kind === 'no' ? 'var(--pl-stage-dropped)' : spec.characters.teal.body;
  return `<div style="background:var(--pl-surface);border:1px solid var(--pl-border);
    border-inline-start:3px solid ${edge};border-radius:var(--radius-md);padding:14px 16px">
    <b style="display:block;font-weight:700;margin-bottom:4px">${title}</b>
    <p style="margin:0;font-size:.9rem;color:var(--pl-fg-secondary)">${body}</p></div>`;
}

/* Fact table: label, machine value, why. The value column is code, so it stays
 * LTR and left-aligned even when the story is previewed in Hebrew. */
export function facts(rows) {
  const cell = (v, extra = '') =>
    `<td style="padding:9px 12px;border-bottom:1px solid rgb(10 10 10 / .08);${extra}">${v}</td>`;
  return `<div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;
    background:var(--pl-surface);border:1px solid var(--pl-border);border-radius:var(--radius-md)">
    <tr style="background:var(--pl-bg)">${['Property', 'Value', 'Why it is that']
      .map((th) => `<th style="text-align:start;padding:9px 12px;border-bottom:1px solid var(--pl-border);${mono}">${th}</th>`)
      .join('')}</tr>
    ${rows.map(([k, v, why]) => `<tr>${cell(k)}${cell(v, mono + ';white-space:nowrap')}
      ${cell(why, 'color:var(--pl-fg-secondary);font-size:.9rem')}</tr>`).join('')}
  </table></div>`;
}

/* Swatch chip carrying a hex the brand owns. */
export function chip(label, hex, sub = '') {
  return `<figure style="margin:0;border:1px solid var(--pl-border);border-radius:var(--radius-md);
    overflow:hidden;background:var(--pl-surface)">
    <div style="height:56px;background:${hex}"></div>
    <figcaption style="padding:8px 10px;${mono};color:var(--pl-fg)">${label}
      <span style="display:block;font-weight:500;color:var(--pl-fg-secondary)">${hex}</span>
      ${sub ? `<span style="display:block;font:500 11px/1.4 inherit;font-family:inherit;color:var(--pl-fg-secondary);margin-top:4px">${sub}</span>` : ''}
    </figcaption></figure>`;
}
