#!/usr/bin/env python3
"""Derive the Storybook Brand/Logo assets from the logo source of truth.

SOURCE OF TRUTH (owned by the Marketing Designer, lives in the agents vault):
    ofir-agents-cloud/assets/logo/

Nothing in this repo is the master. This script pulls from that folder, downsizes
for the web, and writes into stories/brand/assets/ plus a generated measured.json
that the stories read. Every geometric fact shown in the Brand section (aspect
ratio, the empty channels between the heads, the pixel size of each ladder rung)
is MEASURED here off the real artwork rather than typed into a story, for the same
reason Foundations reads styles.css at runtime: a re-typed value rots.

Run:  python3 scripts/build_brand_assets.py [path-to-ofir-agents-cloud]
"""
import json
import re
import shutil
import sys
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parent.parent
VAULT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.home() / "ofir-agents-cloud"
SRC = VAULT / "assets" / "logo"
OUT = REPO / "stories" / "brand" / "assets"

ORDER = ["yellow", "orange", "purple", "teal"]  # reading order, fixed by the spec


def alpha_runs(im, axis):
    """Start/end indices of every band of ink along an axis, from the alpha channel."""
    a = im.getchannel("A").point(lambda v: 255 if v > 16 else 0)
    w, h = im.size
    px = a.load()
    mask = (
        [any(px[x, y] for y in range(h)) for x in range(w)]
        if axis == "x"
        else [any(px[x, y] for x in range(w)) for y in range(h)]
    )
    runs, start = [], None
    for i, v in enumerate(mask):
        if v and start is None:
            start = i
        if not v and start is not None:
            runs.append((start, i - 1))
            start = None
    if start is not None:
        runs.append((start, len(mask) - 1))
    return runs


def save_webp(im, name, width, quality=80):
    if im.width != width:
        im = im.resize((width, max(1, round(im.height * width / im.width))), Image.LANCZOS)
    path = OUT / name
    im.save(path, "WEBP", quality=quality, method=6)
    return {"file": name, "w": im.width, "h": im.height, "kb": round(path.stat().st_size / 1024)}


def main():
    if not SRC.exists():
        sys.exit(f"logo source of truth not found at {SRC}")
    OUT.mkdir(parents=True, exist_ok=True)

    spec = json.loads((SRC / "spec.json").read_text(encoding="utf-8"))
    shutil.copy(SRC / "spec.json", REPO / "stories" / "brand" / "spec.json")

    measured = {
        "_": "GENERATED by scripts/build_brand_assets.py - do not edit. Every number here is "
             "measured off the master artwork in ofir-agents-cloud/assets/logo/out/.",
        "source": "ofir-agents-cloud/assets/logo",
    }

    # ---- the mark ---------------------------------------------------------
    master = Image.open(SRC / "out/system/logo-master.webp").convert("RGBA")
    cols = alpha_runs(master, "x")
    rows = alpha_runs(master, "y")
    assert len(cols) == 2 and len(rows) == 2, f"expected a 2x2, got {cols} {rows}"
    col_gap = cols[1][0] - cols[0][1] - 1
    row_gap = rows[1][0] - rows[0][1] - 1
    avg_head_w = (cols[0][1] - cols[0][0] + 1 + cols[1][1] - cols[1][0] + 1) / 2

    # The AUTHORED proximity constants, read out of the generator rather than
    # retyped. build_system.py applies them to the average TRIMMED head width;
    # the channels measured below are what those constants actually render as.
    build_py = (SRC / "build_system.py").read_text(encoding="utf-8")
    authored = {}
    for key in ("GAP_COLS", "GAP_ROWS"):
        line = next(l for l in build_py.splitlines() if l.startswith(key + " ="))
        authored[key] = float(line.split("=")[1].strip())

    measured["mark"] = {
        "master_px": [master.width, master.height],
        "aspect": round(master.width / master.height, 4),
        "gap_cols_authored": authored["GAP_COLS"],
        "gap_rows_authored": authored["GAP_ROWS"],
        "column_channel_px": col_gap,
        "row_channel_px": row_gap,
        "column_channel_of_mark_width": round(col_gap / master.width, 4),
        "row_channel_of_mark_width": round(row_gap / master.width, 4),
        "column_channel_left_of_mark_width": round(cols[0][1] / master.width, 4),
        "row_channel_top_of_mark_height": round(rows[0][1] / master.height, 4),
        "column_width_px": round(avg_head_w),
        "clear_space_of_mark_width": round(avg_head_w / master.width, 4),
    }
    measured["mark"]["files"] = [save_webp(master.copy(), "mark-master.webp", 760)]

    # ---- the four heads, cut out of the mark itself -----------------------
    # Not re-cut from the generator sources: quadrants of the master are already
    # alpha-clean and already carry the exact scale each head has in the mark.
    quads = {
        "yellow": (cols[0], rows[0]),
        "orange": (cols[1], rows[0]),
        "purple": (cols[0], rows[1]),
        "teal": (cols[1], rows[1]),
    }
    measured["heads"] = {}
    for name in ORDER:
        (x0, x1), (y0, y1) = quads[name]
        head = master.crop((x0, y0, x1 + 1, y1 + 1))
        head = head.crop(head.getchannel("A").point(lambda v: 255 if v > 16 else 0).getbbox())
        measured["heads"][name] = save_webp(head, f"head-{name}.webp", 340)

    # ---- counter-examples for the Do-and-Don't page -----------------------
    # A prohibition you can only read is a prohibition people break. These are
    # DELIBERATELY WRONG renders of the mark, generated from the master so they
    # stay in step with it, and named dont-* so they can never be mistaken for art.
    from PIL import ImageFilter, ImageDraw
    small = master.resize((300, round(300 * master.height / master.width)), Image.LANCZOS)

    # (1) a drop shadow
    pad = 26
    sh = Image.new("RGBA", (small.width + pad * 2, small.height + pad * 2), (0, 0, 0, 0))
    blob = Image.new("RGBA", sh.size, (0, 0, 0, 0))
    blob.paste((64, 45, 31, 150), (pad + 6, pad + 12), small.getchannel("A"))
    sh.alpha_composite(blob.filter(ImageFilter.GaussianBlur(9)))
    sh.alpha_composite(small, (pad, pad))
    measured.setdefault("donts", {})["shadow"] = save_webp(sh, "dont-shadow.webp", 300)

    # (2) a container / plate behind it
    m = 34
    plate = Image.new("RGBA", (small.width + m * 2, small.height + m * 2), (0, 0, 0, 0))
    ImageDraw.Draw(plate).rounded_rectangle([0, 0, plate.width - 1, plate.height - 1],
                                            radius=46, fill=(255, 255, 255, 255),
                                            outline=(210, 190, 168, 255), width=3)
    plate.alpha_composite(small, (m, m))
    measured["donts"]["container"] = save_webp(plate, "dont-container.webp", 300)

    # (3) the four rearranged - top row swapped with the bottom row
    swapped = Image.new("RGBA", master.size, (0, 0, 0, 0))
    top = master.crop((0, 0, master.width, rows[0][1] + 1))
    bot = master.crop((0, rows[1][0], master.width, master.height))
    swapped.alpha_composite(bot, (0, 0))
    swapped.alpha_composite(top, (0, bot.height + row_gap))
    measured["donts"]["rearranged"] = save_webp(swapped, "dont-rearranged.webp", 300)

    # (4) stretched to square
    measured["donts"]["stretched"] = save_webp(
        master.resize((400, 400), Image.LANCZOS), "dont-stretched.webp", 300)

    # ---- the size ladder, PNG rungs shipped as authored -------------------
    measured["ladder"] = []
    for px in (128, 64, 48, 32, 24, 16):
        f = f"logo-{px}.png"
        shutil.copy(SRC / "out/system" / f, OUT / f)
        im = Image.open(OUT / f)
        measured["ladder"].append({"px": px, "file": f, "w": im.width, "h": im.height})

    measured["favicon"] = []
    for px in (48, 32, 16):
        f = f"favicon-{px}.png"
        shutil.copy(SRC / "out/system" / f, OUT / f)
        im = Image.open(OUT / f)
        measured["favicon"].append({"px": px, "file": f, "w": im.width, "h": im.height})

    # ---- the two approved lockups -----------------------------------------
    # Transparent masters, so a story can stand them on any ground with CSS.
    # The -light masters carry cream type and are the ones used on dark.
    measured["lockups"] = {}
    for key, (src, width) in {
        "primary": ("out/lockups/primary-master.webp", 1100),
        "primary_light": ("out/lockups/primary-light-master.webp", 1100),
        "compact": ("out/lockups/compact-master.webp", 460),
        "compact_light": ("out/lockups/compact-light-master.webp", 460),
    }.items():
        im = Image.open(SRC / src).convert("RGBA")
        info = save_webp(im, key.replace("_", "-") + ".webp", width)
        info["master_px"] = list(Image.open(SRC / src).size)
        info["aspect"] = round(info["master_px"][0] / info["master_px"][1], 4)
        measured["lockups"][key] = info

    # the smallest authored rung of each lockup, so the stated minimum is a real
    # file and not a claim: primary at 160px wide is a 64px mark, compact at 120px wide.
    for f in ("primary-160.webp", "compact-120.webp"):
        shutil.copy(SRC / "out/lockups" / f, OUT / f)
        im = Image.open(OUT / f)
        measured["lockups"][f] = {"file": f, "w": im.width, "h": im.height}

    # ---- the approval, recorded as provenance but NOT shipped as artwork ----
    # The artefact is a typeface STUDY sheet with option copy on it. Reproducing a
    # page of options inside the section that states the answer is how a settled
    # decision gets reopened, so the Brand section cites it and does not show it.
    approval = next(SRC.glob("reference/APPROVED-lockup-*.jpg"))
    measured["approval"] = {"artefact": f"reference/{approval.name}",
                            "date": approval.stem.replace("APPROVED-lockup-", ""),
                            "shown_in_storybook": False}

    # ---- the three approved grounds, read out of the exporter --------------
    exp_py = (SRC / "export_lockups.py").read_text(encoding="utf-8")
    grounds = {}
    for key in ("CREAM", "PAPER", "DARK"):
        line = next(l for l in exp_py.splitlines() if l.startswith(key + " ="))
        rgb = [int(n) for n in line.split("(")[1].split(")")[0].split(",")]
        grounds[key.lower()] = "#%02X%02X%02X" % tuple(rgb)

    # ---- the palette, straight out of the spec ----------------------------
    measured["grounds"] = grounds
    measured["palette"] = {
        "ground": spec["ground"],
        "ink": spec["ink"],
        "characters": {n: spec["characters"][n]["body"] for n in ORDER},
        "beanie_navy": spec["characters"]["orange"]["beanie"],
        # the wordmark's two ink values, pulled out of the spec sentence
        "type_on_light": re.findall(r"#[0-9A-Fa-f]{6}", spec["wordmark"]["colour"])[0],
        "type_on_dark": re.findall(r"#[0-9A-Fa-f]{6}", spec["wordmark"]["colour"])[1],
    }

    # ---- the platform-icon tier split, straight out of the spec ------------
    measured["icons"] = spec.get("icons", {})

    (REPO / "stories" / "brand" / "measured.json").write_text(
        json.dumps(measured, indent=2) + "\n", encoding="utf-8"
    )
    total = sum(p.stat().st_size for p in OUT.iterdir())
    print(json.dumps(measured["mark"], indent=2))
    print(f"{len(list(OUT.iterdir()))} files, {round(total/1024)}KB -> {OUT}")


if __name__ == "__main__":
    main()
